makoto_front_homepage:
    path:     /
    defaults: { _controller: MakotoFrontBundle:Default:index }

makoto_front_map:
    path:     /maps
    defaults: { _controller: MakotoFrontBundle:Default:map }
